# H2 Database configuration
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/homework?characterEncoding=UTF8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect